### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by awinecki** [awinecki/amy-vim-coloscheme#1]
Readme should tell a little bit about the project. Now it's a mess and no one knows what the repository is about.

Ok seriously now, I need to update the readme and make some more colorschemes!

**Comment by malukenho** [comment]
:+1:

**Comment by awinecki** [comment]
Lol, just testing ZenHub boards with this ;D sorry for confusion ^^

**Comment by malukenho** [comment]
@awinecki hahahahah
